CREATE INDEX events_type_index ON events(competition_id, event_type, player_id);
CREATE INDEX events_type_outcome_index ON events(competition_id, event_type, outcome, player_id);
CREATE INDEX events_competition_index ON events(competition_id,season_id);
CREATE INDEX events_competition_index2 ON events(competition_id);
CREATE INDEX pass_recipient_index ON pass(competition_id, season_id, recipient_id);
CREATE INDEX pass_technique_index ON pass(competition_id, season_id, technique);
CREATE INDEX shots_first_time ON shot(competition_id, first_time, player_id);
CREATE INDEX shots_competition_player ON shot(competition_id, season_id, player_id); 
CREATE INDEX shots_competition_team ON shot(competition_id, season_id, team_id); 
CREATE INDEX pass_competition_player ON pass(competition_id, season_id, player_id);
CREATE INDEX pass_competition_team ON pass(competition_id, season_id, team_id);